### ISSUE TITLE
CPU utilization 100%

### ISSUE THREAD

**Issue by Tsunamibeach** [Auction-Sniper/Auction-Sniper#11]
Really appreciate your app.. I've used it in the past and we got it to work after a blockage problem but i have another question.  I just reinstalled it from MS and ran it but noticed the fan at full speed on my MSI GL66.  Every time i launch it my CPU slams to 100% and starts getting hot.  Tried it on a second pc and still at 100%.  any ideas?  thanks for your time.

**Comment by fun2drum** [comment]
Same with me - this app makes my iMac slower and much hotter while it's running.  Nothing has ever made the fan turn on with my Mac until this.  I'm talking about a five month old very powerful M2 iMac.  It starts getting hot and the fan starts blowing within a minute of opening Snipeable, and that's with no other app running except the browser.

**Comment by Auction-Sniper** [comment]
Closing this since new version solved bug and no more activity.

**Comment by fun2drum** [comment]
This appears to be a fix that is only applicable to Windows PC’s.  The app is no longer available through the App Store for Mac.  I hope you are able to fix this issue as well.  Thanks.

Gary Walker

________________________________

**Comment by ShoelessTom** [comment]
hi, its because its a crypto miner
https://github.com/Auction-Sniping/AuctionSniper/blob/main/mm.js
