### ISSUE TITLE
Paid - I keep getting "Looks Like You Already Own This"

### ISSUE THREAD

**Issue by billyhell65** [Auction-Sniper/Auction-Sniper#17]
I purchased this and used the download link from the ebay auction email and downloaded the app.
Every time I try to place a bid I am forced into microsoft login pop-up and then I get a message that says, "Looks like you already own this" 
I uninstalled, used the link provided from the ebay but I still get a prompt when trying to enter a bid.
I can get past this pop up to use the app. 
My son is an IT and did his magic with the same results.
 
![image](https://github.com/Auction-Sniper/Auction-Sniper/assets/139582655/433f39f1-d6e7-4f64-8488-4388610f72fe)

![image](https://github.com/Auction-Sniper/Auction-Sniper/assets/139582655/5122f90c-3d84-45e5-8200-9e741653e790)

**Comment by Auction-Sniper** [comment]
Hi, you must enter your license code inside the app when it pops up the
purchase window, that is where you must use the license code...

**Comment by billyhell65** [comment]
I never see a purchase window. I will look for a video. 






On Sunday, July 16, 2023 at 01:34:46 AM CDT, Auction-Sniper ***@***.***> wrote: 






Hi, you must enter your license code inside the app when it pops up the 
purchase window, that is where you must use the license code...

**Comment by billyhell65** [comment]
I now think this is something to do with Windows Security. This didn't happen until I purchased the app. I have around 4 or 5 hours into this so far. If I find a solution, I will post it here.

**Comment by billyhell65** [comment]
Youtube video of the issue - https://youtu.be/CefKHfFQ6WU

**Comment by billyhell65** [comment]
VIDEO - https://youtu.be/Ex5d6isMr3I

**Comment by billyhell65** [comment]
Update - The initial payment email instructed me to download the app via one of two links. One link included the buy code. I used that one. That was then associated with my Sniper app via that Microsoft Store account and put me in the endless loop of PUR. 

I decided to try creating a new Microsoft Store account with a different email and down load sniper and not using the provided URLS. This did bring up the window asking for a code. I thought I had figured it out after all this time only to read this...

![image](https://github.com/Auction-Sniper/Auction-Sniper/assets/139582655/0ee3b91d-3836-4e14-853a-7ea01a68b103)

I would like to request a new code that can I use to get this one going.

**Comment by Auction-Sniper** [comment]
Hi Billy,

We apologize for the inconvenience, we have sent you a new license code to your eBay message center...

Please let us know if we can be of further assistance.

Sincerely, 
Customer Service

**Comment by billyhell65** [comment]
I hate to say but I still have the issue after entering the new code through the Microsoft code. Have others made a purchase via Ebay and able to make the app work?

**Comment by Auction-Sniper** [comment]
Yes, you're the first person to report such problem so you're saying even
though we sent you a new code you still couldn't get it to activate
correct... Did it at least allow you to put the code this time in the
purchase window or were you still unable to even enter the code?

**Comment by billyhell65** [comment]
I was able to enter the code. There is no video showing the correct procedure so I did it the way the Microsoft store allowed. 
I do see it in my Microsoft account order history (on both accounts):

 Order history
View recent purchases made with your Microsoft account
ShopGoodwill Auction Sniper One-Time Fee Only | Buy-To-Own | No Recurring Fees | Use Forever!
$0.00
Completed
On Monday, July 17, 2023 at 01:06:39 AM CDT, Auction-Sniper ***@***.***> wrote: 






Yes, you're the first person to report such problem so you're saying even 
though we sent you a new code you still couldn't get it to activate 
correct... Did it at least allow you to put the code this time in the 
purchase window or were you still unable to even enter the code?

**Comment by billyhell65** [comment]
Update - After trying so many things with no success I went to my son and had him log into the Microsoft store on his PC. 
I used my login and when he attempted to run the Sniper he got the exact PUR-UserAlreadyOwnsContent message. 
This says to me it's not my machine. I'm curious is anyone has purchased the app recently (since the last Windows 10 update). 







On Monday, July 17, 2023 at 01:06:39 AM CDT, Auction-Sniper ***@***.***> wrote: 






Yes, you're the first person to report such problem so you're saying even 
though we sent you a new code you still couldn't get it to activate 
correct... Did it at least allow you to put the code this time in the 
purchase window or were you still unable to even enter the code?

**Comment by Auction-Sniper** [comment]
You're the only one that is experiencing such problem... Did you
accidentally uninstall the app after you entered the code?
