### ISSUE TITLE
PUR-UseralreadyOwnsContent

### ISSUE THREAD

**Issue by billyhell65** [Auction-Sniper/Auction-Sniper#18]
**Initial Steps**
Purchased code from eBay. 
Downloaded app with code. Note - already had app installed.

**Issue** - App will open but when I attempt to load a bid I get a security pop-up and and then a window that states:
PUR-UserAlreadyOwnsConent
![image](https://github.com/Auction-Sniper/Auction-Sniper/assets/139582655/f2a0cc51-ec1d-49d1-bb9e-66277d958787)

**Alternative Actions** - After trying to tweak security settings, uninstalling the app, resseting the store, and more I signed in from a new machine (my son's) and got the same pop-up. This leads me to believe this is not an issue with multiple apps being installed or any settings issues. 

**Alternative Alternative** - I created a new Microsoft store account and got an new code for the app. I attempted to paste this code in the gift certificate option offered by the app when it asks you to buy it. This is the only input window I have yet to locate within the app. The window stated that the code was not applicable - that only gift codes would work. 

I then went into the Microsoft store user tab - redeem code drop down and entered the code there successfully. 
I then received an email stating that the order had been processed. 
I opened the Sniper app and once again had the PUR-UserAlreadyOwnsContent pop-up block me from using the app.

I now have a few days of attempting to make this work. I think I have officially run out of ideas.

**Thoughts**
There was a Windows update I installed a few days ago - maybe that has something to do with it. 
Is there a video of how to intall the code? 
Is there an iOS version of this app? Perhaps I could run it on my phone.

**Comment by Auction-Sniper** [comment]
Hi Billy, please ensure that after you enter the redeem code you don't just
close out the app without following that purchase window all the way thru
otherwise it may redeem the code but not activate...

**Comment by billyhell65** [comment]
Do you have detailed instructions on how to install? I could create a third Microsoft account. (vidoe?)

**Comment by Auction-Sniper** [comment]
There are no installation instructions because it's pretty straight forward
we've never had anyone experience the problems you have before let me see
if I can send you a personalized version...

**Comment by Auction-Sniper** [comment]
Hi Billy, you know what it could be... Our ebay store licensing system is
pretty new so I believe that is why it is not working for you but working
for other users because they all bought theirs inside the app since our
ebay store is only 1 week old... So having said that I will put together a
solution for you and send it to you shortly...

**Comment by billyhell65** [comment]
Great! I appreciate your efforts. Looking forward to getting the app going.

Sent from Yahoo Mail for iPhone


On Monday, July 17, 2023, 6:20 PM, Auction-Sniper ***@***.***> wrote:



Hi Billy, you know what it could be... Our ebay store licensing system is
pretty new so I believe that is why it is not working for you but working
for other users because they all bought theirs inside the app since our
ebay store is only 1 week old... So having said that I will put together a
solution for you and send it to you shortly...

**Comment by billyhell65** [comment]
Any update? 






On Monday, July 17, 2023 at 06:20:31 PM CDT, Auction-Sniper ***@***.***> wrote: 






Hi Billy, you know what it could be... Our ebay store licensing system is 
pretty new so I believe that is why it is not working for you but working 
for other users because they all bought theirs inside the app since our 
ebay store is only 1 week old... So having said that I will put together a 
solution for you and send it to you shortly...

**Comment by billyhell65** [comment]
Any updates? I just lost a bid on a guitar.

**Comment by Auction-Sniper** [comment]
Yes, we are currently in the process of releasing a new update and it
should be released in the next few days, I will keep you posted here...

**Comment by billyhell65** [comment]
IT WORKED! I'M IN!! LIFE IS GOOD! YOU ROCK!

**Comment by Auction-Sniper** [comment]
yes, the new version is released you can update it from your computer which resolves your issue, but also you will need a new promo code and I will provide that to you on your ebay message center...
