### ISSUE TITLE
Paid app not working now

### ISSUE THREAD

**Issue by braintech77** [Auction-Sniper/Auction-Sniper#19]
I paid for the lifetime usage, but now the shopgoodwill sniper program is asking me to pay again.    I was having issues, so I simply logged out.  When I tried logging back in, it all froze up.  I rebooted, and now I cannot use the app unless I pay the $99 again.  Please help.  Isn't this app linked to to my microsoft app purchases?  How do we get this resolved?

Michael

**Comment by braintech77** [comment]
![shopgoodwill Screenshot 2023-07-23 192916](https://github.com/Auction-Sniper/Auction-Sniper/assets/107124004/1091a7d9-abb3-4b03-a815-1c77bbe73a0e)

**Comment by Auction-Sniper** [comment]
Hi Michael,

Please use the following promo code to activate your license: 
braintech778820409074

**Comment by braintech77** [comment]
Hi, that code was invalid within the stripe payment popup window.  Please provide a working code.  Thanks

Michael

**Comment by braintech77** [comment]
![Screenshot 3 2023-07-23 232713](https://github.com/Auction-Sniper/Auction-Sniper/assets/107124004/88985ba2-1f9a-42d8-b991-0989991653ef)

**Comment by Auction-Sniper** [comment]
It is case sensitive, try copying and pasting it exactly how we sent it to
you...

**Comment by braintech77** [comment]
Yes, I definitely copied and pasted it.  It does not work.

**Comment by braintech77** [comment]
The discount box does not allow any lower case letters.

**Comment by braintech77** [comment]
Please provide me a code that is all capital letters and numbers, as lower case letters cannot be used.

**Comment by Auction-Sniper** [comment]
Hi Michael,

Please use this promo code instead:
8820409074

**Comment by braintech77** [comment]
Hi,

I tried that code, but received an error.  So, I completely uninstalled the app, and reinstalled it from the microsoft store.  Now, there is no promo section.  Please help.  Thanks

Michael

**Comment by Auction-Sniper** [comment]
Hi Michael, 

I have re-enabled promo codes for you again, but please finish this time because this following promo code is just for you:
HXQVQBSP

Please note, our system doesn't allow 100% discounts so I gave you 99% discount, which is close enough to zero...

**Comment by braintech77** [comment]
Okay, I just paid the $1 extra.  Do know what caused this error in the first place?   I changed my password on shopgoodwill.  When I tried to log out, and log back in within the shopgoodwill sniper app, I was prompted to pay again.  Is this what happened?

Michael

**Comment by Auction-Sniper** [comment]
Uninstalling and reinstalling sometimes causes this issue...

**Comment by Auction-Sniper** [comment]
We are currently re-writing a new major release which will fix all the latest bugs.

**Comment by braintech77** [comment]
That's great.  Thanks  ;-)

**Comment by braintech77** [comment]
Good morning.  I keep losing so many great auctions due to error messages with the app.   I would like to re-install the app on a dedicated computer, and hopefully things will be better.  Kindly send me another code please.  Thanks

Michael

**Comment by braintech77** [comment]
Hi, 

The app is not working on this computer for me.  I tried disabling my Kaspersky, but had no luck.  I would like to install this app on a dedicated laptop, to try an avoid any further issues.  Kindly send me a code to use.  Thanks so much. 

Michael

**Comment by braintech77** [comment]
Hi,

I only want to use it on one computer.  It is not working on the laptop that I am on.  I have lost several great listings due to error messages.  I want to reinstall the app on "one" dedicated pc.  Please send a new code, so that I can use the app again.  Thanks

Michael

**Comment by Auction-Sniper** [comment]
Hi Michael,

Our system shows that we already issued you a promo code and you used it already on one computer, we can't just give you a new code because we already gave you a code and you are using it on your computer already, if you want to activate your laptop too, you will need to purchase a new license.

**Comment by braintech77** [comment]
The app has been very buggy, and I have lost great auctions.  In effort to fix the issue,  I have deleted the app, and want to reinstall it.  Kindly send me a code, as I have paid for a lifetime membership.  Thanks

Michael

**Comment by braintech77** [comment]
Kindly respond.

**Comment by Auction-Sniper** [comment]
Hi Michael, I will send you the code on Monday however please be advised
this is a one-time courtesy if you delete and reinstall it again next time
you will have to buy a new license so please don't ask for another code
after this one because we already gave you one and you activated it now
you're asking 2nd next time you will need buy another Thank you for your
understanding...

**Comment by braintech77** [comment]
Hi,

You just sent another promo code?  I do not see the code that you sent.  Please send the new code.  Thanks

Michael

**Comment by Auction-Sniper** [comment]
Hi Michael, Monday I will send code!

**Comment by Auction-Sniper** [comment]
Hi Michael,

We have released a new version today that fixes all the sniping issues, please update and I will also send you a code shortly!

Sincerely,
Customer Service

**Comment by Auction-Sniper** [comment]
MICHAEL, WE WON'T BE ABLE TO ASSIST YOU PLEASE CONTACT REPORTAPP@MICROSOFT.COM AND ASK FOR REFUND!

**Comment by Auction-Sniper** [comment]
Hi Michael,

Thank you for your patience as we worked as the issues you reported! We have released a new version which you can download here:

[https://github.com/Auction-Sniper/ShopGoodwill](https://github.com/Auction-Sniper/ShopGoodwill)
