### ISSUE TITLE
Auction Sniper Has Forgotten Me

### ISSUE THREAD

**Issue by BitterBite** [Auction-Sniper/Auction-Sniper#21]
Hi,
I appreciate you taking the time to help me. Here's my issue:
Auction Sniper was not working today so I uninstalled then reinstalled it. It seems to be working now but immediately goes to a $99 checkout page. I've already paid $25 for lifetime license, no fees.
Please help.
Thank you and hope you have a good day,
Renae

**Comment by Auction-Sniper** [comment]
Hi Renae,

Please use the following coupon code to reactivate your license, please do not uninstall and reinstall it again though because this is just a one-time courtesy replacement license, next time you will have to purchase full price so don't lose it this time:

PROMOTION CODE TO USE IS:
RENAE

**Comment by BitterBite** [comment]
Hi,
Thank you for responding. I am putting code RENAE in the promotion box but I am just getting an "invalid code" message in reply.
I've tried it over and over. What am I missing?
Thanks again,
Renae

**Comment by Auction-Sniper** [comment]
Try this one:
07C9BIYX

**Comment by BitterBite** [comment]
Not working either

**Comment by Auction-Sniper** [comment]
For some reason it is not allowing me to do a 100% discount, it only allows the amount directly correlated to your payment, so please try this one instead:
TNZHQEDQ

**Comment by BitterBite** [comment]
That code did work to take $25 off, then I still have to pay $75?
________________________________

**Comment by Auction-Sniper** [comment]
Yes, unfortunately, the system won't allow me to put a credit beyond the payment paid...

**Comment by BitterBite** [comment]
Well, I guess I'll have to get my $25 back then, since this certainly wasn't "a lifetime license with no fees ever"
Thanks anyway and have a nice night.

________________________________

**Comment by Auction-Sniper** [comment]
Ok, have a good day, sorry we couldn't figure it out!
