### ISSUE TITLE
Error Messages

### ISSUE THREAD

**Issue by harbissr** [Auction-Sniper/Auction-Sniper#23]
I keep getting this message after a bid is placed on ShopGoodwill "Error processing the request, please contact your Administrator." It's been happening for a few days now, essentially only one bid can be placed then I have to restart the program. Is this something I can fix on my end or do I need to wait for a patch?

**Comment by Ralins** [comment]
I think we have to wait for a patch. As you mentioned you can restart the program after every snipe and it will work for one bid.. 
Might be able to automate the restarting in the windows task scheduler.

**Comment by billyhell65** [comment]
Since I paid for this app I have yet been able to use it. Let us know when it's fixed.

**Comment by braintech77** [comment]
Yes, so depressing.  I lost several amazing auctions due to this error.  I thought it was my Kaspersky, so I even uninstalled it just to use this sniper, but that definitely was not the issue.  I hope that it gets fixed soon.  So sad.  :-(

**Comment by Ralins** [comment]
> Yes, so depressing. I lost several amazing auctions due to this error. I thought it was my Kaspersky, so I even uninstalled it just to use this sniper, but that definitely was not the issue. I hope that it gets fixed soon. So sad. :-(

SGW has been changing the site around lately / breaking things as per usual.

**Comment by Auction-Sniper** [comment]
Hi Everyone,

We have officially released the new major version of our auction snipers which should be available for download in the next day or so!

The new major version fixes all the latest issues, and is an overall better, smoother, more efficient upgrade, please upgrade to fix...

Please feel free to let us know if you have any further questions or require assistance!

Thank you,
Customer Service
