### ISSUE TITLE
New Version Not Working

### ISSUE THREAD

**Issue by billyhell65** [Auction-Sniper/Auction-Sniper#24]
I put in two snipes. The first one did not work and then the second one disappeared. Also, the menu no longer has options for help, FAQ, turn off the snipe sound (terrible), and most important the link to discussion.

**Comment by Auction-Sniper** [comment]
Hi Billy,

We have released a new version today that fixes all the sniping issues, please update and as for the menu items, we will put some of those items back in the next version, we appreciate your suggestions!

Thank you!
Customer Service

**Comment by billyhell65** [comment]
I just realized I lost another auction with no bid from your app. This is 3 items that the sniper didn't bid on and after the auction it just wasn't listed anymore. I'm super unhappy. This is with the latest update.

**Comment by Auction-Sniper** [comment]
Please contact reportapp@microsoft.com and let them know you are unhappy and want a refund because they won't let us post any updates without giving us any hassle so we won't be able to update or fix the app because of them, get a refund!!!

**Comment by billyhell65** [comment]
I purchased this through Paypal.  I would prefer a working app but after loosing multiple items I would not trust the app again. I purchased this on Ebay. You could refund my money is you wanted to. I waited to leave a review until now.

**Comment by Auction-Sniper** [comment]
Hi Billy, I understand we have been a lot of hassles with Microsoft so
unfortunately we have disconnected our relationship with them and we are
now going to distribute the software on our own website so you are welcome
to use they were preventing us from fixing.

**Comment by billyhell65** [comment]
A stand alone app would be best. What is your website address? 
    On Thursday, August 17, 2023 at 12:33:19 PM CDT, Auction-Sniper ***@***.***> wrote:  
 
 

Hi Billy, I understand we have been a lot of hassles with Microsoft so
unfortunately we have disconnected our relationship with them and we are
now going to distribute the software on our own website so you are welcome
to use they were preventing us from fixing.

**Comment by Auction-Sniper** [comment]
Hi Billy,

We have released a new version of with all the fixes to the issues that you reported that can now be download here:

[https://github.com/Auction-Sniper/ShopGoodwill](https://github.com/Auction-Sniper/ShopGoodwill)

**Comment by billyhell65** [comment]
How do I put my code into this version of the app?

**Comment by Auction-Sniper** [comment]
Hi Billy,

Please use the following new code instead:

TSUQUSEN

**Comment by billyhell65** [comment]
I applied the code - price went to $1. I paid. I see it withdrawn from my account but the app continues to ask for payment. I tried to apply the code again but now says it is expired. 
    On Wednesday, August 23, 2023 at 08:59:35 AM CDT, Auction Sniper ***@***.***> wrote:  
 
 


Hi Billy,

Please use the following new code instead:

TSUQUSEN

**Comment by Auction-Sniper** [comment]
It should have given activation confirmation ensure you allow it thru your
firewall typically asks when you first launch the program  also please try
re-downloading zip from our site Snipeable.com also I will void your $1
payment and send you new code shortly...

**Comment by billyhell65** [comment]
Unhandled ErrorError: listen EADDRINUSE: address already in use 127.0.0.1:54645    at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)    at __node_internal_uvExceptionWithHostPort (node:internal/errors:589:12)    at Server.setupListenHandle [as _listen2] (node:net:1740:16)    at listenInCluster (node:net:1788:12)    at doListen (node:net:1937:7)    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
I did verify not other Sniper Auction apps were running. End tasked them all and clicked the app again. The above is what I get. 

    On Wednesday, August 23, 2023 at 12:22:49 PM CDT, Auction Sniper ***@***.***> wrote:  
 
 

It should have given activation confirmation ensure you allow it thru your
firewall typically asks when you first launch the program also please try
re-downloading zip from our site Snipeable.com also I will void your $1
payment and send you new code shortly...

**Comment by Auction-Sniper** [comment]
Ok, yes that is the error that is keeping your activation from working
which is already fixed on our website, please redownload and reinstall to
fix that error from http://Snipeable.com please restart your computer as
well to free up port error, the latest package on our website closes down
properly

**Comment by Auction-Sniper** [comment]
Hi Billy,

Here is your new activation code, use this to try again after redownloading and reinstalling the latest version:
UVU0TL7K

**Comment by billyhell65** [comment]
I find the sniper works if I restart my computer before each use and leave the app on during the snipe time. I have a question. What happens if I add a sniper bid AND bid on the item through the Shopgoodwill site? I've lost a few key items and want to make sure I get the piece.

**Comment by Auction-Sniper** [comment]
Hi Billy,

To answer your question, you can bid thru the shopgoodwill website and/or still use the bid sniper app together, so to answer your question, yes, they can work concurrently together, if that's what you wish to do...

Regarding, the latest bugs and issues, we released a new version today that resolves all the latest sgw timing bugs and more you can download the latest version here:

http://ShopGoodwillSniper.com

The new version also adds alot of new menu timing options, you can now adjust the timing on the snipes because every users connection speed is different, the best solution, was to add the timing option and then leave it to user to choose...

Please feel free to let us know if you have any further questions or need assistance...

Thank you,
Snipeable.com
Customer Service

**Comment by billyhell65** [comment]
I had a shirt I was waiting on for 2 weeks. I put a bid in on another shirt (1 minute before the shirt I actually wanted) to make sure the Sniper worked this time. Your app made the bid on the first shirt but didn't make a bid on the second. So once again I have lost another item due to your app. 

    On Monday, August 28, 2023 at 06:18:17 PM CDT, Auction Sniper ***@***.***> wrote:  
 
 


Hi Billy,

To answer your question, you can bid thru the shopgoodwill website and/or still use the bid sniper app together, so to answer your question, yes, they can work concurrently together, if that's what you wish to do...

Regarding, the latest bugs and issues, we released a new version today that resolves all the latest sgw timing bugs and more you can download the latest version here:

http://ShopGoodwillSniper.com

The new version also adds alot of new menu timing options, you can now adjust the timing on the snipes because every users connection speed is different, the best solution, was to add the timing option and then leave it to user to choose...

Please feel free to let us know if you have any further questions or need assistance...

Thank you,
Snipeable.com
Customer Service

**Comment by Auction-Sniper** [comment]
Hi Billy,

Did you download and install the latest version? If you still missed it
with the latest version, then you might just have been outbid or actually
just missed that auction, now on the other hand we have another user that
bids on 100s of items a day using the sniper and he just emailed us today
telling us that he wins 9/10 auctions with the sniper software, so thats
almost all of them, occasionally some might miss, but 99% success rate is
pretty good still so I'm not sure what to tell you except, it will get
better over time, tune your settings, and maybe even bid using the sniper
and the browser both like you said...

Best Regards,
Customer Service

**Comment by Auction-Sniper** [comment]
Hi Billy,

We have added new 10, 15, 20, 30 and 60 seconds sniper timing options to the main menu in a new version released today you can download it here on our website:

http://ShopGoodwillSniper.com

**Comment by billyhell65** [comment]
Do I need to uninstall with every new update? The software doesn't seem to have an uninstall option. 
    On Thursday, August 31, 2023 at 09:47:14 PM CDT, Auction Sniper ***@***.***> wrote:  
 
 


Hi Billy,

We have added new 10, 15, 20, 30 and 60 seconds sniper timing options to the main menu in a new version released today you can download it here on our website:

http://ShopGoodwillSniper.com

**Comment by Auction-Sniper** [comment]
Hi Billy, there is no need to uninstall because the installer script
automatically takes care of all that for you, simply download zip, then
extract, then double click the install file and it will automatically
update!
