### ISSUE TITLE
WRONG TIMEZONE!

### ISSUE THREAD

**Issue by bjwhitely** [Auction-Sniper/Auction-Sniper#9]
After daylight savings time ended last weekend for PST (Pacific Standard Time) the Shopgoodwill Auction-Sniper time is off by an hour:
For my bid for item ID 154413314 with an end time of 1/09/2022 06:30:00 PM PT
![image](https://user-images.githubusercontent.com/117947122/201203664-ff21dbf2-6d22-4c84-830b-eb47988a67d2.png)
Shopgoodwill Auction-Sniper submitted my snipper bid at 11/9/2022, 5:30:00 PM - an hour before the auction ended!
![image](https://user-images.githubusercontent.com/117947122/201203483-4abd298d-4cb3-419e-953a-c968bab56994.png)
This ONLY started happening after DST ended.  Please fix the time zone problem for PST.
Thank-you.

**Comment by razormd** [comment]
Is this website for "snipeable"?

**Comment by bjwhitely** [comment]
I've tried both "snipeable.exe" and "ShopGoodwill Auction Sniper.exe" and they both have the same problem with the time being off by 1 hour.
Thanks.

**Comment by Auction-Sniper** [comment]
> I've tried both "snipeable.exe" and "ShopGoodwill Auction Sniper.exe" and they both have the same problem with the time being off by 1 hour.
> 
> Thanks. 

Hi BjWhitely,

The time zone from Snipeable is synced by ntp time servers and then it is compared against ur local computers time zone to determine the correct time zone offset so it doesn't really have a setting for time zone because it is suppose to get the correct time zone automatically so here are the steps I recommend to correct your local time zone problem, 1st please ensure your local computers time is correct and then try restarting the Snipeable app completely and/or restart your computer to ensure all the times on your computer are properly updated, the other part of the time that calculates the auction ends datetime are automatically synced with the actual auctioneers website in your case ShopGoodwill.com so in your specific case the problem could be coming from either one of those places, please try the steps I mentioned and please let us know if the problem still persists after that so we can dig deeper!

**Comment by Auction-Sniper** [comment]
> Is this website for "snipeable"?

Yes, razormd this is the official website for Snipeable!

**Comment by razormd** [comment]
I uninstalled "snipeable" and restarted the computer to insure the time was correct. I then redownloaded and reinstalled it, but it is still off by one hour.

**Comment by Auction-Sniper** [comment]
> I uninstalled "snipeable" and restarted the computer to insure the time was correct. I then redownloaded and reinstalled it, but it is still off by one hour.

Can u please confirm the time on your local computer is correct please by looking down in the system tray area on your computer desktop?

**Comment by bjwhitely** [comment]
I also uninstalled "snipeable" / checked the time settings / rebooted / reinstalled "snipeable" and still off an hour.  Again, this ONLY became a problem when we switched off of DST on 11/6/22!
Correct computer time - PST:
![image](https://user-images.githubusercontent.com/117947122/201777879-d251de5e-a440-47d2-a930-e05eb46fd2cc.png)
ShopGoodwill time - end of auction 6:41pm:
![image](https://user-images.githubusercontent.com/117947122/201778027-f40e732a-fb78-40f2-983c-f29e4c8345b2.png)
Snipeable time - end of auction 5:41pm
![image](https://user-images.githubusercontent.com/117947122/201778317-7fb915d0-1d67-424b-b8c3-adb923584cb4.png)

**Comment by Auction-Sniper** [comment]
> I also uninstalled "snipeable" / checked the time settings / rebooted / reinstalled "snipeable" and still off an hour.  Again, this ONLY became a problem when we switched off of DST on 11/6/22!
> 
> Correct computer time - PST:
> 
> ![image](https://user-images.githubusercontent.com/117947122/201777879-d251de5e-a440-47d2-a930-e05eb46fd2cc.png)
> 
> ShopGoodwill time - end of auction 6:41pm:
> 
> ![image](https://user-images.githubusercontent.com/117947122/201778027-f40e732a-fb78-40f2-983c-f29e4c8345b2.png)
> 
> Snipeable time - end of auction 5:41pm
> 
> ![image](https://user-images.githubusercontent.com/117947122/201778317-7fb915d0-1d67-424b-b8c3-adb923584cb4.png)
> 
> 
> 
> 

Ok Thank You for that information, the shopgoodwill servers might still have the old time let us investigate and we will get back to you shortly!

**Comment by razormd** [comment]
Ditto for me as to "bjwhitely" results. Appreciate your effort. It's an excellent little program -- when it works. Thanks.

**Comment by Auction-Sniper** [comment]
> Ditto for me as to "bjwhitely" results. Appreciate your effort. It's an excellent little program -- when it works. Thanks.

We are investigating the source of the incorrect time zone offset now...

**Comment by Auction-Sniper** [comment]
> Ditto for me as to "bjwhitely" results. Appreciate your effort. It's an excellent little program -- when it works. Thanks.

Hi razormd,

I am glad to report we have concluded our investigation into the issue you reported, and have found the bug and fixed it and released a new version that you can now update from the App Store!

Please let us know if we can be of further assistance.

Thank you,
Customer Service

**Comment by Auction-Sniper** [comment]
> After daylight savings time ended last weekend for PST (Pacific Standard Time) the Shopgoodwill Auction-Sniper time is off by an hour:
> 
> For my bid for item ID 154413314 with an end time of 1/09/2022 06:30:00 PM PT
> 
> ![image](https://user-images.githubusercontent.com/117947122/201203664-ff21dbf2-6d22-4c84-830b-eb47988a67d2.png)
> 
> Shopgoodwill Auction-Sniper submitted my snipper bid at 11/9/2022, 5:30:00 PM - an hour before the auction ended!
> 
> ![image](https://user-images.githubusercontent.com/117947122/201203483-4abd298d-4cb3-419e-953a-c968bab56994.png)
> 
> This ONLY started happening after DST ended.  Please fix the time zone problem for PST.
> 
> Thank-you.

Hi bjWhitely,

I am glad to report we have concluded our investigation into the issue you reported, and have found the bug and fixed it and released a new version that you can now update from the App Store!

Please let us know if we can be of further assistance.

Thank you,
Customer Service

**Comment by Auction-Sniper** [comment]
> Wahoo! Timezone problem is fixed - thanks for fixing this.

It was our pleasure, the issue was it was converting PT time to PDT time but it should have been PST time, so that was causing it to be 1 hour off!
